using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using VerifyCS = AutoInvoke.Generator.UnitTests.Verifiers.CSharpSourceGeneratorVerifier<AutoInvoke.Generator.InvokeGenerator>;

namespace AutoInvoke.Generator.UnitTests;
[TestClass]
public class HelloWorldGeneratorUnitTests {
    private const string Attribute = @"// <auto-generated/>
#nullable enable

namespace AutoInvoke;
[System.AttributeUsage(System.AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
[System.Diagnostics.Conditional(""AutoNotifyGenerator_DEBUG"")]
internal sealed class FindAndInvokeAttribute : System.Attribute
{
#pragma warning disable CS0169 // Remove unused parameter

#pragma warning disable IDE0060 // Remove unused parameter

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

    public FindAndInvokeAttribute()
    {
    }

    public FindAndInvokeAttribute(string pattern)
    {
    }

    public string MethodName { get; set; }
    public bool CallForAbstractClasses { get; set; }
    public bool CallForInterfaces { get; set; }
    public bool CallForStructs { get; set; }
    public bool CallForClasses { get; set; }
    public bool CallForRecords { get; set; }
#pragma warning restore CS0169 // Remove unused parameter

#pragma warning restore IDE0060 // Remove unused parameter

#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

}";

    [TestMethod]
    public async Task GenerateSimple() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter {
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo {
		
	}
}

class Foo {}
class Bar {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Foo>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }
    [TestMethod]
    public async Task GenerateSynchron() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter {
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo {
		
	}
}

class Foo {}
class Bar :Foo {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Foo>();
        GetHelloWorld<T1.T2.Bar>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task GenerateAsync() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static System.Threading.Tasks.Task GetHelloWorld<T>() where T : Foo {
		return System.Threading.Tasks.Task.CompletedTask;
	}
}

class Foo {}
class Bar :Foo {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static System.Threading.Tasks.Task[] GetHelloWorld() {
        return new []{GetHelloWorld<T1.T2.Foo>(), GetHelloWorld<T1.T2.Bar>()};
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task DoNotGenerateAbstract() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo {
		
	}
}

abstract class Foo {}
class Bar : Foo{}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }
    [TestMethod]
    public async Task DoNotGenerateStatic() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() {
		
	}
}

static class Foo {}
class Bar {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar>();
        GetHelloWorld<AutoInvoke.FindAndInvokeAttribute>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task SelfReferecningGeneric() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo<T> {
		
	}
}

interface Foo<TData> where TData : Foo<TData> {}
class Bar : Foo<Bar> {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }
    [TestMethod]
    public async Task SelfReferecningNestedGeneric() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo<Bar<T>> {
		
	}
}

interface Foo<TData>{}
interface Bar<TData2> {}
class My : Foo<Bar<My>> {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.My>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task BoundGeneric() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo<string> {
		
	}
}

interface Foo<TData>  {}
class Bar : Foo<string> {}
class Bar2 : Foo<int> {}


";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }
    [TestMethod]
    public async Task BoundWithUnboundGeneric() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>() where T : Foo<string, T> {
		
	}
}

interface Foo<TData,TData2>  {}
class Bar : Foo<string,Bar> {}

";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task MethodWithParameters() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>(string f1, int f2) where T : Foo<string, T> {
		
	}
}

interface Foo<TData,TData2>  {}
class Bar : Foo<string,Bar> {}

";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld(string f1, int f2) {
        GetHelloWorld<T1.T2.Bar>(f1, f2);
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task MethodWithParamsParameters() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T>(string f1, params int[] f2) where T : Foo<string, T> {
		
	}
}

interface Foo<TData,TData2>  {}
class Bar : Foo<string,Bar> {}

";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld(string f1, int[] f2) {
        GetHelloWorld<T1.T2.Bar>(f1, f2);
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }

    [TestMethod]
    public async Task InterfaceWithMultipleGenerics() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T,T2>() where T : Foo<T2, T> where T2 : System.Attribute {
		
	}
}

interface Foo<TData,TData2> where TData2 :  Foo<TData,TData2> {}
class Bar : Foo<System.FlagsAttribute,Bar> {}
class Bar2 : Foo<System.MTAThreadAttribute,Bar2> {}
class Bar3 : Foo<Object,Bar3> {}

";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
        GetHelloWorld<T1.T2.Bar, System.FlagsAttribute>();
        GetHelloWorld<T1.T2.Bar2, System.MTAThreadAttribute>();
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, ("attribute.g.cs", Attribute),
            ("T1.T2.class.GetHelloWorld.g.cs", global)
            );
    }
    [TestMethod]
    public async Task InterfaceWithMultipleGenericsInvalid() {
        string code = @"
using System;
namespace T1.T2;
internal static partial class GlobalNamespaceGreeter
{
	[AutoInvoke.FindAndInvoke]
	public static void GetHelloWorld<T,T2>()  {
		
	}
}

interface Foo<TData,TData2> where TData2 :  Foo<TData,TData2> {}
class Bar : Foo<System.FlagsAttribute,Bar> {}
class Bar2 : Foo<System.MTAThreadAttribute,Bar2> {}
class Bar3 : Foo<Object,Bar3> {}

";

        string global = @"// <auto-generated/>
#nullable enable
namespace T1.T2;
partial class GlobalNamespaceGreeter {
    private static void GetHelloWorld() {
    }
}
";
        await VerifyCS.VerifyGeneratorAsync(code, DiagnosticResult.CompilerError("IG0001").WithSpan(7, 34, 7, 40), ("attribute.g.cs", Attribute)
            );
    }
}

